import { ValidationResult, Paper } from '@/types'

export function generateMarkdownReport(
  topic: string,
  summary: string | null,
  gaps: string | null,
  hypotheses: string | null,
  experimentPlan: string | null,
  validationResult: ValidationResult | null,
  papers: Paper[]
): string {
  const date = new Date().toLocaleDateString()

  let report = '# AI Scientist Research Report\n'
  report += `**Topic:** ${topic}\n`
  report += `**Date:** ${date}\n\n`

  report += '## 1. Research Summary\n'
  report += `${summary || 'No summary generated.'}\n\n`

  report += '## 2. Identified Research Gaps\n'
  report += `${gaps || 'No gaps identified.'}\n\n`

  report += '## 3. Proposed Hypotheses\n'
  report += `${hypotheses || 'No hypotheses generated.'}\n\n`

  if (experimentPlan) {
    report += '## 4. Experiment Plan\n'
    report += `${experimentPlan}\n\n`
  }

  if (validationResult) {
    report += '## 5. Scientific Validation (CDM + NDI)\n'
    report += `### Overall Assessment: **${validationResult.classification}**\n\n`

    report += '| Metric | Score | Interpretation |\n'
    report += '| :--- | :--- | :--- |\n'
    report += `| **Stability (CDM)** | ${(validationResult.metrics.stability_score * 100).toFixed(1)}% | ${validationResult.cdm.stability} |\n`
    report += `| **Novelty (NDI)** | ${(validationResult.metrics.novelty_score * 100).toFixed(1)}% | ${validationResult.ndi.novelty} |\n`
    report += `| **Overall Viability** | ${(validationResult.metrics.viability_score * 100).toFixed(1)}% | - |\n\n`

    report += '### Domain Fragmentation (CDM Details)\n'
    report += `> ${validationResult.cdm.conflict_summary}\n\n`

    if (validationResult.cdm.details && validationResult.cdm.details.length > 0) {
      report += '#### Top Contradicting/Supporting Pairs\n'
      validationResult.cdm.details.forEach((detail, i) => {
        const type = detail.classification === 'CONTRADICT'
          ? '[CONTRADICT]'
          : detail.classification === 'SUPPORT'
            ? '[SUPPORT]'
            : '[NEUTRAL]'
        report += `**Pair #${i + 1}: ${type}**\n`
        report += `*Source:* ${detail.source}\n`
        report += `*Comparison:* ${detail.raw_response}\n\n`
      })
    }
  }

  if (papers.length > 0) {
    report += '## 6. References (Top Papers)\n'
    papers.forEach((paper, i) => {
      report += `${i + 1}. **${paper.title}** (${paper.authors.slice(0, 2).join(', ')}${paper.authors.length > 2 ? ' et al.' : ''})\n`
      report += `   [PDF Link](${paper.pdf_url})\n\n`
    })
  }

  report += '\n---\n*Report generated by AI Scientist - Scientific Validation Edition*'

  return report
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const a = document.createElement('a')
  const file = new Blob([content], { type: contentType })
  a.href = URL.createObjectURL(file)
  a.download = fileName
  a.click()
  URL.revokeObjectURL(a.href)
}
